### ISSUE TITLE
Can't play any stream

### ISSUE THREAD

**Issue by mmakarios** [fgl27/smarttv-twitch#34]
I just installed the app and it is not playing any streams. It justs shows the loading spinner for about 2 minutes and then "stream has ended". Clips and videos works.

I installed the master version to check the logs as you instructed in another issue, and here are the logs from the Chrome console, using Debug As: 

```
language is en_US
2019-06-03 01:17:04.924 Screens.js:6 InitScreens place holder
2019-06-03 01:17:05.010 VM181:1 Entering setDisplayRect
2019-06-03 01:17:05.016 VM181:1 adding listener
2019-06-03 01:17:05.018 VM181:1 Entered AVPlayManager.prepareAsync()
2019-06-03 01:17:05.091 webapis.min.js:1 [productinfo.js] getFirmware  begin
2019-06-03 01:17:05.109 webapis.min.js:1 [productinfo.js] getFirmware  end [object Object]
2019-06-03 01:17:05.109 webapis.min.js:1 [productinfo.js] getFirmware message data T-KTMUABC-1270.3
2019-06-03 01:17:05.110 webapis.min.js:1 [productinfo.js] getModel  begin
2019-06-03 01:17:05.111 webapis.min.js:1 [productinfo.js] getModel  end [object Object]
2019-06-03 01:17:05.112 webapis.min.js:1 [productinfo.js] getModel message data UMU6103
2019-06-03 01:17:05.112 Main.js:737 App version: 051919
2019-06-03 01:17:05.114 Main.js:752 Tizen Version: 3.0 | TV: UMU6103 | FW: T-KTMUABC-1270.3
2019-06-03 01:17:10.175 webapis.min.js:1 [network.js] addNetworkStateChangeListener  success
2019-06-03 01:17:10.176 webapis.min.js:1 [network.js] listenerId 0
2019-06-03 01:17:15.060 SmartHub.js:40 Cannot read property 'setPreviewData' of undefined
2019-06-03 01:17:18.618 webapis.min.js:1 [webapi.js] cbArr length: 1, then remove Callback!
2019-06-03 01:17:19.342 Play.js:653 Play_onPlayer: date: Sun Jun 02 2019 21:17:19 GMT-0700 (PDT)
2019-06-03 01:17:19.343 Play.js:654 Play_onPlayer: 

"https://video-weaver.sao01.hls.ttvnw.net/v1/playlist/CtQD2kVWuV_TukBTdFUe5c…bWUULEmx0hjqjCrVO4255X4sCuEhCPqUuY0W0G6e-8L0Qm-iqcGgzywk6vwButdqTuqjc.m3u8"

2019-06-03 01:17:19.367 VM181:1 Entering setDisplayRect
2019-06-03 01:17:19.370 VM181:1 adding listener
2019-06-03 01:17:19.371 VM181:1 Entered AVPlayManager.prepareAsync()
2019-06-03 01:17:28.395 Play.js:653 Play_onPlayer: date: Sun Jun 02 2019 21:17:28 GMT-0700 (PDT)
2019-06-03 01:17:28.396 Play.js:654 Play_onPlayer: 

"https://video-weaver.sao01.hls.ttvnw.net/v1/playlist/CtQD2kVWuV_TukBTdFUe5c…bWUULEmx0hjqjCrVO4255X4sCuEhCPqUuY0W0G6e-8L0Qm-iqcGgzywk6vwButdqTuqjc.m3u8"

2019-06-03 01:17:28.630 VM181:1 Entering setDisplayRect
2019-06-03 01:17:28.633 VM181:1 adding listener
2019-06-03 01:17:28.634 VM181:1 Entered AVPlayManager.prepareAsync()
2019-06-03 01:17:37.657 Play.js:653 Play_onPlayer: date: Sun Jun 02 2019 21:17:37 GMT-0700 (PDT)
2019-06-03 01:17:37.658 Play.js:654 Play_onPlayer: 

"https://video-weaver.sao01.hls.ttvnw.net/v1/playlist/CtQD2kVWuV_TukBTdFUe5c…bWUULEmx0hjqjCrVO4255X4sCuEhCPqUuY0W0G6e-8L0Qm-iqcGgzywk6vwButdqTuqjc.m3u8"

2019-06-03 01:17:38.026 VM181:1 Entering setDisplayRect
2019-06-03 01:17:38.029 VM181:1 adding listener
2019-06-03 01:17:38.029 VM181:1 Entered AVPlayManager.prepareAsync()
2019-06-03 01:17:47.493 Play.js:653 Play_onPlayer: date: Sun Jun 02 2019 21:17:47 GMT-0700 (PDT)
2019-06-03 01:17:47.493 Play.js:654 Play_onPlayer: 

"https://video-weaver.sao01.hls.ttvnw.net/v1/playlist/CtID3N7qldxg7PgWoJUwAa…8TVaPrrLcuw2OyAifybttbgV3DRIQ07_YRtVhkagRcz_vEtDmZhoMOwG7isnSzPIOtMUc.m3u8"

2019-06-03 01:17:47.717 VM181:1 Entering setDisplayRect
2019-06-03 01:17:47.724 VM181:1 adding listener
2019-06-03 01:17:47.725 VM181:1 Entered AVPlayManager.prepareAsync()
2019-06-03 01:17:56.743 Play.js:653 Play_onPlayer: date: Sun Jun 02 2019 21:17:56 GMT-0700 (PDT)
2019-06-03 01:17:56.743 Play.js:654 Play_onPlayer: 

"https://video-weaver.sao01.hls.ttvnw.net/v1/playlist/CtID3N7qldxg7PgWoJUwAa…8TVaPrrLcuw2OyAifybttbgV3DRIQ07_YRtVhkagRcz_vEtDmZhoMOwG7isnSzPIOtMUc.m3u8"

2019-06-03 01:17:57.208 VM181:1 Entering setDisplayRect
2019-06-03 01:17:57.213 VM181:1 adding listener
2019-06-03 01:17:57.215 VM181:1 Entered AVPlayManager.prepareAsync()
2019-06-03 01:18:06.442 Play.js:653 Play_onPlayer: date: Sun Jun 02 2019 21:18:06 GMT-0700 (PDT)
2019-06-03 01:18:06.443 Play.js:654 Play_onPlayer: 

"https://video-weaver.sao01.hls.ttvnw.net/v1/playlist/CtIDFfceN1UMWuOx7u1qP4…vRnLnbMft57J9fmTmJfb5N0Rm-BIQEtMQq7R9gBeu1pYpH06GUBoMhoeyE5phS0bZNadE.m3u8"

2019-06-03 01:18:07.073 VM181:1 Entering setDisplayRect
2019-06-03 01:18:07.077 VM181:1 adding listener
2019-06-03 01:18:07.077 VM181:1 Entered AVPlayManager.prepareAsync()
2019-06-03 01:18:16.099 Play.js:653 Play_onPlayer: date: Sun Jun 02 2019 21:18:16 GMT-0700 (PDT)
2019-06-03 01:18:16.101 Play.js:654 Play_onPlayer: 

"https://video-weaver.sao01.hls.ttvnw.net/v1/playlist/CtIDFfceN1UMWuOx7u1qP4…vRnLnbMft57J9fmTmJfb5N0Rm-BIQEtMQq7R9gBeu1pYpH06GUBoMhoeyE5phS0bZNadE.m3u8"

2019-06-03 01:18:16.658 VM181:1 Entering setDisplayRect
2019-06-03 01:18:16.677 VM181:1 adding listener
2019-06-03 01:18:16.678 VM181:1 Entered AVPlayManager.prepareAsync()
2019-06-03 01:18:25.943 Play.js:653 Play_onPlayer: date: Sun Jun 02 2019 21:18:25 GMT-0700 (PDT)
2019-06-03 01:18:25.943 Play.js:654 Play_onPlayer: 

"https://video-weaver.sao01.hls.ttvnw.net/v1/playlist/CtIDvRpq7MD361gSfCTsg1…wAqCYLQThJWdSVXj0CAISD2vxLBIQS5UCQDKLrZ0U3Cx-noFNZBoM9p0AH73DumBc9mjs.m3u8"

2019-06-03 01:18:26.066 VM181:1 Entering setDisplayRect
2019-06-03 01:18:26.072 VM181:1 adding listener
2019-06-03 01:18:26.073 VM181:1 Entered AVPlayManager.prepareAsync()
2019-06-03 01:18:35.088 Play.js:653 Play_onPlayer: date: Sun Jun 02 2019 21:18:35 GMT-0700 (PDT)
2019-06-03 01:18:35.089 Play.js:654 Play_onPlayer: 

"https://video-weaver.sao01.hls.ttvnw.net/v1/playlist/CtIDvRpq7MD361gSfCTsg1…wAqCYLQThJWdSVXj0CAISD2vxLBIQS5UCQDKLrZ0U3Cx-noFNZBoM9p0AH73DumBc9mjs.m3u8"

2019-06-03 01:18:35.410 VM181:1 Entering setDisplayRect
2019-06-03 01:18:35.416 VM181:1 adding listener
2019-06-03 01:18:35.417 VM181:1 Entered AVPlayManager.prepareAsync()
2019-06-03 01:18:44.635 Play.js:653 Play_onPlayer: date: Sun Jun 02 2019 21:18:44 GMT-0700 (PDT)
2019-06-03 01:18:44.636 Play.js:654 Play_onPlayer: 

"https://video-weaver.sao01.hls.ttvnw.net/v1/playlist/CtID6dizCB6cYOGuXsrmlT…zGhX8-5GIKRtBUcrLMupYV6pBHxIQU72F1011QIvLiz388Chf1hoMkK9Ru--pP-bVBYIq.m3u8"

2019-06-03 01:18:44.926 VM181:1 Entering setDisplayRect
2019-06-03 01:18:44.946 VM181:1 adding listener
2019-06-03 01:18:44.947 VM181:1 Entered AVPlayManager.prepareAsync()
2019-06-03 01:18:53.973 Play.js:653 Play_onPlayer: date: Sun Jun 02 2019 21:18:53 GMT-0700 (PDT)
2019-06-03 01:18:53.974 Play.js:654 Play_onPlayer: 

"https://video-weaver.sao01.hls.ttvnw.net/v1/playlist/CtID6dizCB6cYOGuXsrmlT…zGhX8-5GIKRtBUcrLMupYV6pBHxIQU72F1011QIvLiz388Chf1hoMkK9Ru--pP-bVBYIq.m3u8"

2019-06-03 01:18:54.108 VM181:1 Entering setDisplayRect
2019-06-03 01:18:54.148 VM181:1 adding listener
2019-06-03 01:18:54.150 VM181:1 Entered AVPlayManager.prepareAsync()
2019-06-03 01:19:03.409 Play.js:653 Play_onPlayer: date: Sun Jun 02 2019 21:19:03 GMT-0700 (PDT)
2019-06-03 01:19:03.410 Play.js:654 Play_onPlayer: 

"https://video-weaver.sao01.hls.ttvnw.net/v1/playlist/CtIDN7WFkaRkcT6kIcplBK…kQmrFxk8XyYHZCP0uajXmHpQFOxIQTgIdKTMYBZrUoI_bxwaRWBoMfaiSTL6ErUjILh8a.m3u8"

2019-06-03 01:19:04.015 VM181:1 Entering setDisplayRect
2019-06-03 01:19:04.021 VM181:1 adding listener
2019-06-03 01:19:04.022 VM181:1 Entered AVPlayManager.prepareAsync()
2019-06-03 01:19:13.042 Play.js:653 Play_onPlayer: date: Sun Jun 02 2019 21:19:13 GMT-0700 (PDT)
2019-06-03 01:19:13.043 Play.js:654 Play_onPlayer: 

"https://video-weaver.sao01.hls.ttvnw.net/v1/playlist/CtIDN7WFkaRkcT6kIcplBK…kQmrFxk8XyYHZCP0uajXmHpQFOxIQTgIdKTMYBZrUoI_bxwaRWBoMfaiSTL6ErUjILh8a.m3u8"

2019-06-03 01:19:13.569 VM181:1 Entering setDisplayRect
2019-06-03 01:19:13.594 VM181:1 adding listener
2019-06-03 01:19:13.595 VM181:1 Entered AVPlayManager.prepareAsync()
2019-06-03 01:19:26.791 webapis.min.js:1 [webapi.js] cbArr length: 1, then remove Callback!
```

Also, when I try to "Debug As" or "Run As" the master version, Tizen Studio shows a dialog saying "Incompatible profile. Project requires tv-samsung-public-profile, but target has none profile.", and it runs anyway. Is this expected? It doesn't happen with the release version.

Thank you!

**Comment by fgl27** [comment]
This seems related to #15, buts yours TV is running a new FW in relation to the one showed on #15.
Seems Samsung partially fix the issue as before wasn't possible to play a thing.

I going to ask in #15 see if there is improve and if there is I merge the two issue as I don't have a solution for now as is a FW bug, and samsung must fix it, but they today aren't accepting reports from none partners developers about issue, so isn't possible to ask they for help.

If the FW on yours TV update, or you find a way to inform samsung about the problem and they answer or is fixed let us know.

Regarding profile, you can just dismiss that I have no idea what tizen whats there as it doesn't show for me on any version of the app.

**Comment by TheW0LVERIN3** [comment]
Could you report it here?
https://www.tizen.org/community/bug-tracker/how-report-bugs

**Comment by fgl27** [comment]
Does this issue persist?

**Comment by mmakarios** [comment]
I don't think there were any firmware updates, so I guess the issue persists. I will test again this week.

**Comment by mmakarios** [comment]
Still not working, but now, during the "stream has ended. exiting in 3..." message, the stream starts to play. After the countdown, the app returns to the main menu. So I guess that something that gets enabled/disabled when the message starts is preventing the stream to load? What do you think?

**Comment by fgl27** [comment]
Donwload the source https://github.com/fgl27/smarttv-twitch/archive/master.zip instal and share the logs so I can see.

**Comment by fgl27** [comment]
Also press a D-pad key up, down etc, after the countdown start, it will prevent it from exit and tell me what happens there... share the solg of it also.

**Comment by megalhaes** [comment]
Hi. 

I'm having the same problem. I have this app running perfectly on an exact same Samsung TV model installed ( version  4.0.1 V2.) a few months ago and has seemingly the older user interface. The problem is exactly like mmakarios described, when the loop ends during the "stream has ended. exiting in 3..." message, the stream starts to play. After the countdown, the app returns to the main menu. If I press the D-pad up to prevent the automatic exit stream keeps playing on the background, albeit with bad quality, until I manually exit. I'm having problems generating a log, this is the best I could do, version installed is 4.0.1 V3:

```
Main_IsNotBrowser tizen = true
master.js:1 language is pt-PT
master.js:1 InitScreens place holder
webapis.min.js:1 [productinfo.js] getFirmware  begin
webapis.min.js:1 [productinfo.js] getFirmware  end [object Object]
webapis.min.js:1 [productinfo.js] getFirmware message data T-KTMDEUC-1270.3
webapis.min.js:1 [productinfo.js] getModel  begin
webapis.min.js:1 [productinfo.js] getModel  end [object Object]
webapis.min.js:1 [productinfo.js] getModel message data UMU650R
master.js:1 App version: 080619
VM53:1 Entering setDisplayRect
VM53:1 adding listener
VM53:1 Entered AVPlayManager.prepareAsync()
VM53:1 Entering setDisplayRect
VM53:1 adding listener
VM53:1 Entered AVPlayManager.prepareAsync()
VM53:1 Entering setDisplayRect
VM53:1 adding listener
VM53:1 Entered AVPlayManager.prepareAsync()
VM53:1 Entering setDisplayRect
VM53:1 adding listener
VM53:1 Entered AVPlayManager.prepareAsync()
VM53:1 Entering setDisplayRect
VM53:1 adding listener
VM53:1 Entered AVPlayManager.prepareAsync()
VM53:1 Entering setDisplayRect
VM53:1 adding listener
VM53:1 Entered AVPlayManager.prepareAsync()
VM53:1 Entering setDisplayRect
VM53:1 adding listener
VM53:1 Entered AVPlayManager.prepareAsync()
VM53:1 Entering setDisplayRect
VM53:1 adding listener
VM53:1 Entered AVPlayManager.prepareAsync()
VM53:1 Entering setDisplayRect
VM53:1 adding listener
VM53:1 Entered AVPlayManager.prepareAsync()
VM53:1 Entering setDisplayRect
VM53:1 adding listener
VM53:1 Entered AVPlayManager.prepareAsync()
VM53:1 Entering setDisplayRect
VM53:1 adding listener
VM53:1 Entered AVPlayManager.prepareAsync()
VM53:1 Entering setDisplayRect
VM53:1 adding listener
VM53:1 Entered AVPlayManager.prepareAsync()
VM53:1 Entering setDisplayRect
VM53:1 adding listener
VM53:1 Entered AVPlayManager.prepareAsync()
VM53:1 Entering setDisplayRect
VM53:1 adding listener
VM53:1 Entered AVPlayManager.prepareAsync()
webapis.min.js:1 [webapi.js] cbArr length: 1, then remove Callback!
```

**Comment by fgl27** [comment]
@megalhaes as I wrote above

> Donwload the source https://github.com/fgl27/smarttv-twitch/archive/master.zip instal and share the logs so I can see.

The released can't be used for loging.

**Comment by fgl27** [comment]
I push the above see if that fixes the issue, the on the release, if doesn't help log from the source

**Comment by megalhaes** [comment]
Ran a debug on the source master, stream loaded sucessfully:

`Main_IsNotBrowser tizen = true
Main.js:192 language is pt-PT
Screens.js:6 InitScreens place holder
webapis.min.js:1 [productinfo.js] getFirmware  begin
webapis.min.js:1 [productinfo.js] getFirmware  end [object Object]
webapis.min.js:1 [productinfo.js] getFirmware message data T-KTMDEUC-1270.3
webapis.min.js:1 [productinfo.js] getModel  begin
webapis.min.js:1 [productinfo.js] getModel  end [object Object]
webapis.min.js:1 [productinfo.js] getModel message data UMU650R
Main.js:745 App version: 080619
Main.js:758 Tizen Version: 3.0 | TV: UMU650R | FW: T-KTMDEUC-1270.3
VM75:1 Entering setDisplayRect
VM75:1 adding listener
VM75:1 Entered AVPlayManager.prepareAsync()
Play.js:738 Play_onPlayer: date: Thu Aug 15 2019 19:29:56 GMT+0100 (WEST)
Play.js:739 Play_onPlayer: 

"https://video-weaver.mad01.hls.ttvnw.net/v1/playlist/CtYDjI0Juxa2tMCFWJDbig…YkOoAgazizsQKZwmmYXrK1t7cYSEBCduiS6ZB9v4QcHZvWb3HEaDMoP5KjvDUEPpksnMg.m3u8"

VM75:1 Entering setDisplayRect
VM75:1 adding listener
Play.js:676 onbufferingstart: date: Thu Aug 15 2019 19:30:08 GMT+0100 (WEST)
Play.js:702 onbufferingprogress > 98: date: Thu Aug 15 2019 19:30:10 GMT+0100 (WEST)
Play.js:686 onbufferingcomplete: date: Thu Aug 15 2019 19:30:10 GMT+0100 (WEST)`

Should I install the regular version?

**Comment by fgl27** [comment]
Yes install the release as that auto update it self, the source will not receive updates, and if you already  had the released installed before is already there as the source version doesn't install it.

**Comment by fgl27** [comment]
@mmakarios seems all good recheck and close this

**Comment by mmakarios** [comment]
It's working! Thank you!
