### ISSUE TITLE
Streams not playing (Unable to get stream link issue)

### ISSUE THREAD

**Issue by Supernoodles1990** [fgl27/smarttv-twitch#68]
Every stream says for example "Lirik has ended" or "Vader has ended" clips work fine but vods also do the same thing.

All was working fine until around 30 mins ago

**Comment by toremi** [comment]
I am experiencing the same issue. 
During the time where it doesn't work, I observed the following behavior:
Thumbnails and everything looks normal and loads fine. Live video and Past broadcasts exit instantly with the message "Streamer has ended". Clips work however. 

It seems unaffected by app or TV restarts, but usually resolves itself after some time passes. I've experienced it a few times over the last few days.

**Comment by MantaDroid** [comment]
Describe the bug
When trying to start a stream it ends up saying "stream has ended".

Started happening after turning off the TV while watching a Twitch stream earlier today.
I try to start new streams, I refresh a few times.

I've just tried uninstalling (removing) the app and re-installing it via Tizen, but same error persists. Would love to see suggestions on how to fix :(

To Reproduce
Don't know how to reproduce it. Currently it is

start app
refresh live streams
click on a live strem
get "stream has ended" message
Check video below.

Expected behavior
Stream should start and work fine.

Video
Streamable video showing what happens - https://streamable.com/wip1y

Operation system (if is a installation problem):

OS: Windows 10, but this shouldnt matter as it worked fine before today.


@toremi how do I close my thread? Am a noob to github.

**Comment by fgl27** [comment]
#67 is actually the first one about this.

The first time this happened short it didn't give me any time to try to fix it, as it just return back to work just after 5 10 min, this time I didn't get the issue or was offline when it happened.

The first time Twitch server was OK but responding with a error message, nothing was done before during or after to the app (on the functions related to get a stream link) so this is just a issue related to Twitch changing things and adding bugs.

The server is returning 410 error equal to what #58 returned.

I add all workarounds that was added to fix #58 but I don't know if it takes any effect as those aren't the same api call but do return same error.

I also add a new warning **Unable to get stream link issue** this will show on the screen whenever this issues happens, and there one can just come here and let us know that is happening and if I'm online on that moment I take a look to see if I can fix the issue when is happening and prevent from ever do it again.

So let me know if you see that warning.

**Comment by dlaviati** [comment]
Hey Felipe, it's happening right now (2019-11-08 7:40 pm UTC time)

**Comment by Le-maki** [comment]
Happening to me right now too, thumbnails are appearing correctly, but when I click on it I immediately have the error "unable to get stream link issue", and then "the stream has ended".
Don't hesitate if i can help in any way!

**Comment by fgl27** [comment]
I push a workaround force close the app by holding back key and it must work again after a re open.

**Comment by Le-maki** [comment]
@fgl27 working perfectly, thank you very much!

**Comment by dlaviati** [comment]
Fantastic, thanks a lot! :)

**Comment by AshXK** [comment]
@fgl27  Thank you very much.

**Comment by rohkeaID** [comment]
The problem  is still here. At least for me:
Force quit didn't help, so I took the latest version from releases and rebuilt, but it is also doesn't solve the problem

For some reasons app did not work 4 days ago, 3 days ago everything was fine, but today it is back

**Comment by fgl27** [comment]
@rohkeaID is all working here.
Share a log so I can see what is going on...
how to log in this post https://github.com/fgl27/smarttv-twitch/issues/5#issuecomment-466170992

after you see the information on the console window, open some LIVE streams and some VODs

**Comment by rohkeaID** [comment]
@fgl27 

alright. got it.
the code from master branch works fine and the problem was with a 410 error message in a release version

**Comment by fgl27** [comment]
no is not they are the same code.

what shows for you in the about of the release app? the version?

**Comment by rohkeaID** [comment]
wait wait..)

I know that the code from Master branch and the latest Release version are two different versions.
I mean, I just did some tests, checked errors in debug mode and found what I did wrong. 

Well, the problem (https://github.com/fgl27/smarttv-twitch/issues/68#issuecomment-552905203) initially happened in a Released version. I checked what was wrong - it was a problem caused by changed Twitch API with error message 410

With latest updates from a Master branch everything works fine now. Thanks
App version: 4.0.1.111119TEST

**Comment by fgl27** [comment]
see this picture... the code are the same you are not using the release.

![image](https://user-images.githubusercontent.com/13755892/68690579-fdb15000-0550-11ea-8197-cfbb15fd9d6c.png)

why the release version would be **App version: 4.0.1.111119TEST**?

you didn't download the correct zip and that is way you see the **TEST** the same you will show when installing from the repo aka Master branch.

From that picture you can see that you download the source zip, that wrong zip is now 10 days old and full of bugs. the correct zip is this 
https://github.com/fgl27/smarttv-twitch/releases/download/4.0.1_V4/4.0.1_V4.zip

That is only 12kb and yes is the exactly copy of the master branch because even it not having the code on the zip, every time you open the app it download the source from the web, that is way it is so small and always works and keep it self update.

**Comment by rohkeaID** [comment]
@fgl27 Please, read my message carefully once again..

**Comment by fgl27** [comment]
you don't wanna run the release fine don't I don't care. Just be sure that I warn you that you are not running the release version AKA the only version that I advise to use.

that is simple as open the about and see a big TEST word that is not there on the real release version.

@rohkeaID you don't know how to read.

**Comment by rohkeaID** [comment]
C'mon. Just to make a story shorter: with latest updates of a main repo everything is fine. And I am NOT using a release version since it has a version of 102919 and  full of bugs (just check the link here https://github.com/fgl27/smarttv-twitch/archive/4.0.1_V4.tar.gz). I am using 111219 (or whatever from the latests) and everything is OK and I'm very happy. 

Thanks for the App once again. I'm really appreciate

**Comment by fgl27** [comment]
**since when a **tar.gz** file is a zip file?**
I told you you was using the wrong file any one can tell by the app version, I share to you a screenshot with a bold red arrow point to the correct file to download, also share the direct link of that file and you insist in tell me that the release is bad.

Of course is bad but is not the release is you that is all wrong.

Have fun when the app stop working because you insist in use the wrong file don't came complaining here.

**Comment by rohkeaID** [comment]
dude, I'm gonna quit the discussion since u r too toxic and your English is extremely terrible. 
don't explain me what to do with codes.. The main idea of all my todays posts is that problem from the first one is solved since 111119 version (or whatever). Thats it. Nothing more.

best to u

**Comment by fgl27** [comment]
I teach myself on how to speak english I know I not perfect, but I know the difference of zip file and a tar.gz file, and is not because my english is bad that you don't get I share to you **a picture with a big red bold arrow** point to the correct zip and you still don't get it you still don't download the write file and insist that I'm wrong, **what you expect when someone keeps trying to explain something to you and you insist that the person is wrong and you are write?** that I'm going to keep it cool?

you don't even tried to get since the start you think you are right and I the one that did the project and know how it works is wrong, I keep trying to explain you and you keep not even trying to understand...

How in that position you expect that I will not sound disturbed or as you say "toxic", I'm not toxik I iss of that you are so much unplite and un care that you don't even give a FUCK to see a picture and download the correct file, look to yours own behavior, you didn't even admit that you had **DOWNLOAD THE WRONG FILE** and that is the whole problem since the beginning you ask I give then you don't care, how much you wanna me to give if you keep insisting you are write when since the beginning you didn't even had the correct file? you shared the wrong file link look to yours own behavier
